In [2]:
import os
import pandas as pd

In [3]:
path = "coinbase_stream_23-04-09_21-20-26.198844.parquet"

In [5]:
df = pd.read_parquet(os.path.abspath(f"../data/{path}"))
df.head()

,ts,product_id,ask_price1,ask_price2,ask_price3,ask_price4,ask_price5,ask_price6,ask_price7,ask_price8,...,bid_volume11,bid_volume12,bid_volume13,bid_volume14,bid_volume15,bid_volume16,bid_volume17,bid_volume18,bid_volume19,bid_volume20
0,2023-04-10 01:17:50.601800+00:00,ETH-USD,1854.45,1854.46,1854.47,1854.48,1854.49,1854.5,1854.51,1854.52,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2023-04-10 01:17:50.602444+00:00,ETH-USD,1854.45,1854.46,1854.47,1854.48,1854.49,1854.5,1854.51,1854.52,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2023-04-10 01:17:50.602471+00:00,ETH-USD,1854.45,1854.46,1854.47,1854.48,1854.49,1854.5,1854.51,1854.52,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2023-04-10 01:17:50.602480+00:00,ETH-USD,1854.45,1854.46,1854.47,1854.48,1854.49,1854.5,1854.51,1854.52,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2023-04-10 01:17:50.603522+00:00,ETH-USD,1854.45,1854.46,1854.47,1854.48,1854.49,1854.5,1854.51,1854.52,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df.bid_volume17

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
99995    0.0
99996    0.0
99997    0.0
99998    0.0
99999    0.0
Name: bid_volume17, Length: 100000, dtype: float64